export const earringData=[
    {
        id: 1,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/sixteen-stone-by-tiffanyearrings-10907152_1025985_ED.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Earrings",
        title: "Gold & Diamond Earrings",
        oldPrice: 12300,
        price: 1100,
        popularity: 1.5,
        rating: 3.10,
        date: "2024-01-20",
    },
    {
        id: 2,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/sixteen-stone-by-tiffanynarrow-earrings-74038042_1080663_ED.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Earrings",
        title: "Gold & Diamond Earrings",
        oldPrice: 11300,
        price: 1000,
        popularity: 1,
        rating: 2.9,
        date: "2024-01-20",
    },
    {
        id: 3,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/tiffany-knotdrop-earrings-70300419_1033867_ED.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Earrings",
        title: "Tiffany Knot Drop Earrings",
        oldPrice: 1500,
        price: 1300,
        popularity: 2.5,
        rating: 2.10,
        date: "2024-01-20",
    },
    {
        id: 4,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/tiffany-knothoop-earrings-75123639_1084613_ED.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Earrings",
        title: "Golden Earrings with white Pearls",
        oldPrice: 12300,
        price: 9900,
        popularity: 5,
        rating: 5.5,
        date: "2024-01-20",
    },
        {
        id: 5,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/tiffany-solitaire-diamond-stud-earrings-14041419_921472_ED_M.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Rings",
        title: "Couple Silver Ring Diamond",
        oldPrice: 12600,
        price: 10000,
        popularity: 4.5,
        rating: 10.0,
        date: "2024-01-20",
    },
]