export const earringData=[
    {
        id: 1,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/sixteen-stone-by-tiffanyearrings-10907152_1025985_ED.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Earrings",
        title: "Gold & Diamond Earrings",
        oldPrice: "$123.00",
        price: "$11.00",
    },
    {
        id: 2,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/sixteen-stone-by-tiffanynarrow-earrings-74038042_1080663_ED.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Earrings",
        title: "Gold & Diamond Earrings",
        oldPrice: "$113.00",
        price: "$10.00",
    },
    {
        id: 3,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/tiffany-knotdrop-earrings-70300419_1033867_ED.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Earrings",
        title: "Tiffany Knot Drop Earrings",
        oldPrice: "$15.00",
        price: "$13.00",
    },
    {
        id: 4,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/tiffany-knothoop-earrings-75123639_1084613_ED.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Earrings",
        title: "Golden Earrings with white Pearls",
        oldPrice: "$123.00",
        price: "$99.00",
    },
        {
        id: 5,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/tiffany-solitaire-diamond-stud-earrings-14041419_921472_ED_M.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Rings",
        title: "Couple Silver Ring Diamond",
        oldPrice: "$123.00",
        price: "$99.00",
    },
]