export const ringData=[
    {
        id: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8uFfBzfWFvUVZErPD2DohEemrrxC0nBKqNQ&s",
        type: "Rings",
        title: "Couple Silver Ring Diamond",
        oldPrice: 12300,
        price: 11500,
        popularity: 4,
        rating: 4.3,
        date: "2024-05-01",
    },
    {
        id: 2,
        image: "https://media.tiffany.com/is/image/Tiffany/EcomBrowseM/jean-schlumberger-by-tiffanysixteen-stone-ring-23429446_1041816_ED_M.jpg?defaultImage=NoImageAvailableInternal&fmt=webp",
        type: "Rings",
        title: "Couple Silver Pendent Diamond",
        oldPrice: 12500,
        price: 2000,
        popularity: 5,
        rating: 3.3,
        date: "2024-05-01",
    },
    {
        id: 3,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHZsiqPruws4cW5133IIF2GUesLWhbzjiHJg&s",
        type: "Rings",
        title: "Couple Gold and Diamond Ring",
        oldPrice: 12900,
        price: 22900,
        popularity: 2,
        rating: 2.3,
        date: "2024-05-01",
    },
    {
    id: 4,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8uFfBzfWFvUVZErPD2DohEemrrxC0nBKqNQ&s",
    type: "Rings",
    title: "Couple Silver Ring Diamond",
    oldPrice: 1400,
    price: 1550,
    popularity: 2,
    rating: 3.5,
    date: "2024-02-28",
  },
    {
    id: 5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHZsiqPruws4cW5133IIF2GUesLWhbzjiHJg&s",
    type: "Rings",
    title: "Couple Gold and Diamond Ring",
    oldPrice: 1100,
    price: 1500,
    popularity: 1,
    rating: 2.9,
    date: "2024-01-20",
   },
]