export const storeData = [
  {
    id: 1,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8uFfBzfWFvUVZErPD2DohEemrrxC0nBKqNQ&s",
    type: "Rings",
    title: "Couple Silver Ring Diamond",
    oldPrice: 200,
    price: 150,
    popularity: 4,
    rating: 4.3,
    date: "2024-05-01",
  },
  {
    id: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIn6ds2nPPIxvS-N8c1QFD_Iaoe24y63EFXg&sA",
    type: "Pendent",
    title: "Couple Silver Pendent Diamond",
    oldPrice: 500,
    price: 450,
    popularity: 3,
    rating: 3.9,
    date: "2024-04-15",
  },
  {
    id: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHZsiqPruws4cW5133IIF2GUesLWhbzjiHJg&s",
    type: "Rings",
    title: "Couple Gold and Diamond Ring",
    oldPrice: 1000,
    price: 900,
    popularity: 5,
    rating: 4.7,
    date: "2024-06-10",
  },
  {
    id: 4,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxkZ0nogrxMzSxxvZwkvFJs9djoilYAV29MQ&s",
    type: "Earrings",
    title: "Golden Earrings with white Pearls",
    oldPrice: 350,
    price: 300,
    popularity: 4,
    rating: 4.2,
    date: "2024-03-25",
  },
  {
    id: 5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8uFfBzfWFvUVZErPD2DohEemrrxC0nBKqNQ&s",
    type: "Rings",
    title: "Couple Silver Ring Diamond",
    oldPrice: 400,
    price: 450,
    popularity: 2,
    rating: 3.5,
    date: "2024-02-28",
  },
  {
    id: 6,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIn6ds2nPPIxvS-N8c1QFD_Iaoe24y63EFXg&sA",
    type: "Pendent",
    title: "Couple Silver Pendent Diamond",
    oldPrice: 1000,
    price: 980,
    popularity: 5,
    rating: 4.9,
    date: "2024-07-05",
  },
  {
    id: 7,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHZsiqPruws4cW5133IIF2GUesLWhbzjiHJg&s",
    type: "Rings",
    title: "Couple Gold and Diamond Ring",
    oldPrice: 1100,
    price: 1500,
    popularity: 1,
    rating: 2.9,
    date: "2024-01-20",
  },
  {
    id: 8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxkZ0nogrxMzSxxvZwkvFJs9djoilYAV29MQ&s",
    type: "Earrings",
    title: "Golden Earrings with white Pearls",
    oldPrice: 1200,
    price: 1000,
    popularity: 3,
    rating: 3.8,
    date: "2024-05-30",
  },
];
