export const storeData=[
    {
        id: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8uFfBzfWFvUVZErPD2DohEemrrxC0nBKqNQ&s",
        type: "Rings",
        title: "Couple Silver Ring Diamond",
        oldPrice: "$123.00",
        price: "$99.00",
    },
    {
        id: 2,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIn6ds2nPPIxvS-N8c1QFD_Iaoe24y63EFXg&sA",
        type: "Pendent",
        title: "Couple Silver Pendent Diamond",
        oldPrice: "$123.00",
        price: "$99.00",
    },
    {
        id: 3,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHZsiqPruws4cW5133IIF2GUesLWhbzjiHJg&s",
        type: "Rings",
        title: "Couple Gold and Diamond Ring",
        oldPrice: "$123.00",
        price: "$99.00",
    },
    {
        id: 4,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxkZ0nogrxMzSxxvZwkvFJs9djoilYAV29MQ&s",
        type: "Earrings",
        title: "Golden Earrings with white Pearls",
        oldPrice: "$123.00",
        price: "$99.00",
    },
        {
        id: 5,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8uFfBzfWFvUVZErPD2DohEemrrxC0nBKqNQ&s",
        type: "Rings",
        title: "Couple Silver Ring Diamond",
        oldPrice: "$123.00",
        price: "$99.00",
    },
    {
        id: 6,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIn6ds2nPPIxvS-N8c1QFD_Iaoe24y63EFXg&sA",
        type: "Pendent",
        title: "Couple Silver Pendent Diamond",
        oldPrice: "$123.00",
        price: "$99.00",
    },
    {
        id: 7,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHZsiqPruws4cW5133IIF2GUesLWhbzjiHJg&s",
        type: "Rings",
        title: "Couple Gold and Diamond Ring",
        oldPrice: "$123.00",
        price: "$99.00",
    },
    {
        id: 8,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxkZ0nogrxMzSxxvZwkvFJs9djoilYAV29MQ&s",
        type: "Earrings",
        title: "Golden Earrings with white Pearls",
        oldPrice: "$123.00",
        price: "$99.00",
    },
];